import { NextRequest, NextResponse } from 'next/server';
import { and, desc, eq, inArray, sql } from 'drizzle-orm';
import { db } from '@/db';
import { content, enquiries, listings, rateLimits, reviews, saves, users } from '@/db/schema';
import { currentUser, hashPassword, checkPassword, createSession, logout } from '@/lib/auth';
import { seedDirectory } from '@/lib/seed';
import { contentKeys, publicSettings } from '@/lib/content';
import { timingSafeEqual } from 'node:crypto';
export const runtime = 'nodejs';
const fail = (message: string, status = 400) => NextResponse.json({ error: message }, { status });
const clean = (value: unknown, max = 300) => typeof value === 'string' ? value.trim().slice(0, max) : '';
const validEmail = (value: string) => value.length <= 254 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const validHttpUrl = (value: string) => { try { return ['http:', 'https:'].includes(new URL(value).protocol); } catch { return false; } };
const positiveId = (value: unknown) => { const n = Number(value); return Number.isInteger(n) && n > 0 ? n : null; };
function requestIp(req: NextRequest) { return clean(req.headers.get('x-real-ip') || req.headers.get('x-forwarded-for')?.split(',')[0] || 'unknown', 120); }
async function consumeRateLimit(key: string, limit: number, windowMinutes: number) {
 const result = await db.execute(sql`INSERT INTO ${rateLimits} (key, window_start, count) VALUES (${key}, now(), 1) ON CONFLICT (key) DO UPDATE SET count = CASE WHEN ${rateLimits.windowStart} < now() - make_interval(mins => ${windowMinutes}) THEN 1 ELSE ${rateLimits.count} + 1 END, window_start = CASE WHEN ${rateLimits.windowStart} < now() - make_interval(mins => ${windowMinutes}) THEN now() ELSE ${rateLimits.windowStart} END RETURNING count`);
 return Number((result.rows[0] as { count?: number | string } | undefined)?.count ?? 0) <= limit;
}
function sameOrigin(req: NextRequest) {
 const origin = req.headers.get('origin'); if (!origin) return true;
 try { const expectedHost = req.headers.get('x-forwarded-host') || req.headers.get('host') || req.nextUrl.host; const expectedProto = req.headers.get('x-forwarded-proto')?.split(',')[0].trim() || req.nextUrl.protocol.replace(':', ''); const actual = new URL(origin); return actual.host === expectedHost && actual.protocol === `${expectedProto}:`; } catch { return false; }
}
export async function GET(req: NextRequest) {
 try {
  await seedDirectory(); const user = await currentUser(); const section = req.nextUrl.searchParams.get('section');
  if (section === 'detail') { const id = positiveId(req.nextUrl.searchParams.get('id')); if (!id) return fail('Invalid listing id.'); const [listing] = await db.select().from(listings).where(eq(listings.id, id)); if (!listing || (listing.status !== 'approved' && user?.role !== 'superadmin' && user?.role !== 'staff' && user?.id !== listing.ownerId)) return fail('Listing not found', 404); await db.update(listings).set({ views: sql`${listings.views} + 1` }).where(eq(listings.id, id)); const feedback = await db.select({ id: reviews.id, name: users.name, rating: reviews.rating, comment: reviews.comment, createdAt: reviews.createdAt }).from(reviews).innerJoin(users, eq(reviews.userId, users.id)).where(eq(reviews.listingId, id)).orderBy(desc(reviews.createdAt)); return NextResponse.json({ listing, reviews: feedback }, { headers: { 'Cache-Control': 'no-store' } }); }
  if (section === 'dashboard') { if (!user) return fail('Please sign in', 401); const admin = ['superadmin', 'staff'].includes(user.role); const mine = admin ? await db.select().from(listings).orderBy(desc(listings.createdAt)) : await db.select().from(listings).where(eq(listings.ownerId, user.id)).orderBy(desc(listings.createdAt)); const leads = admin ? await db.select().from(enquiries).orderBy(desc(enquiries.createdAt)) : await db.select().from(enquiries).where(mine.length ? inArray(enquiries.listingId, mine.map(l => l.id)) : eq(enquiries.userId, user.id)).orderBy(desc(enquiries.createdAt)); const members = user.role === 'superadmin' ? await db.select({ id: users.id, name: users.name, email: users.email, role: users.role, suspended: users.suspended }).from(users).orderBy(users.name) : []; return NextResponse.json({ listings: mine, enquiries: leads, users: members, content: admin ? await db.select().from(content).where(inArray(content.key, contentKeys)) : [] }, { headers: { 'Cache-Control': 'no-store' } }); }
  const publicListings = await db.select().from(listings).where(eq(listings.status, 'approved')).orderBy(desc(listings.featured), listings.id); const saved = user ? await db.select({ listingId: saves.listingId }).from(saves).where(eq(saves.userId, user.id)) : []; const settings = publicSettings(await db.select().from(content).where(inArray(content.key, contentKeys))); return NextResponse.json({ listings: publicListings, user, saved: saved.map(s => s.listingId), settings }, { headers: { 'Cache-Control': 'no-store' } });
 } catch (error) { console.error('GET /api/platform failed', error); return fail('Unable to load data. Please try again.', 500); }
}
export async function POST(req: NextRequest) {
 try {
  if (!sameOrigin(req)) return fail('Invalid request origin', 403); if (!(req.headers.get('content-type') || '').toLowerCase().includes('application/json')) return fail('JSON requests are required.', 415);
  const b = await req.json(); if (!b || typeof b !== 'object' || Array.isArray(b)) return fail('Invalid request body.'); const action = clean(b.action, 40); const user = await currentUser(); const admin = !!user && ['superadmin', 'staff'].includes(user.role); const ip = requestIp(req);
  if (action === 'register' || action === 'login') {
   if (!(await consumeRateLimit(`auth:ip:${ip}`, 15, 15))) return fail('Too many authentication attempts. Try again in 15 minutes.', 429); const email = clean(b.email, 254).toLowerCase(); const password = typeof b.password === 'string' ? b.password : ''; if (!validEmail(email) || password.length < 8 || password.length > 128) return fail('Use a valid email and a password of 8–128 characters.'); if (!(await consumeRateLimit(`auth:email:${email}`, 10, 15))) return fail('Too many attempts for this account. Try again in 15 minutes.'); const [existing] = await db.select().from(users).where(eq(users.email, email));
   if (action === 'login') { if (!existing || !checkPassword(password, existing.passwordHash) || existing.suspended) return fail('Email or password is incorrect, or account is unavailable.', 401); await createSession(existing.id); return NextResponse.json({ success: true }); }
   if (existing) return fail('An account already exists with this email. Please sign in.', 409); const name = clean(b.name, 100); if (!name) return fail('Please enter your name.'); let role = b.role === 'creator' ? 'creator' : 'business'; const adminKey = clean(b.adminKey, 256); if (adminKey) { const configured = process.env.ADMIN_SETUP_KEY; const [existingAdmin] = await db.select({ id: users.id }).from(users).where(eq(users.role, 'superadmin')).limit(1); if (existingAdmin) return fail('Administrator setup is already complete.', 403); if (!configured || Buffer.byteLength(configured) !== Buffer.byteLength(adminKey) || !timingSafeEqual(Buffer.from(configured), Buffer.from(adminKey))) return fail('Invalid administrator setup key.', 403); role = 'superadmin'; } const [created] = await db.insert(users).values({ name, email, passwordHash: hashPassword(password), role }).returning({ id: users.id }); await createSession(created.id); return NextResponse.json({ success: true });
  }
  if (action === 'logout') { await logout(); return NextResponse.json({ success: true }); }
  if (action === 'enquiry') { if (!(await consumeRateLimit(`enquiry:ip:${ip}`, 10, 60))) return fail('Too many messages. Please try again later.', 429); const name = clean(b.name, 100), email = clean(b.email, 254), message = clean(b.message, 3000); if (!name || !validEmail(email) || message.length < 10) return fail('Enter your name, a valid email and a message of at least 10 characters.'); const type = ['enquiry','report','promotion','collaboration','event'].includes(b.type) ? b.type : 'enquiry'; const listingId = b.listingId == null || b.listingId === '' ? null : positiveId(b.listingId); if (b.listingId != null && listingId == null) return fail('Invalid listing id.'); if (listingId) { const [target] = await db.select({ id: listings.id }).from(listings).where(and(eq(listings.id, listingId), eq(listings.status, 'approved'))); if (!target) return fail('Listing not found.', 404); } await db.insert(enquiries).values({ listingId, userId: user?.id, name, email, message, type }); return NextResponse.json({ success: true }); }
  if (!user) return fail('Please sign in to continue.', 401);
  if (action === 'submit' || action === 'edit') { if (!(await consumeRateLimit(`listing:${user.id}`, 10, 60))) return fail('Submission limit reached. Please try again later.', 429); const data = { name: clean(b.name, 120), kind: ['business','creator','place'].includes(b.kind) ? b.kind : 'business', category: clean(b.category, 80), location: clean(b.location, 80), description: clean(b.description, 5000), image: clean(b.image, 1500) || 'https://images.pexels.com/photos/4324492/pexels-photo-4324492.jpeg?auto=compress&cs=tinysrgb&w=1000', phone: clean(b.phone, 30), website: clean(b.website, 1000), address: clean(b.address, 500), hours: clean(b.hours, 150), price: clean(b.price, 150) }; if (!data.name || !data.category || !data.location || data.description.length < 20) return fail('Complete the required fields and add a description of at least 20 characters.'); if ((!validHttpUrl(data.image) && !/^\/api\/uploads\/[0-9a-f-]{36}$/.test(data.image)) || (data.website && !validHttpUrl(data.website))) return fail('Image and website URLs must start with https:// or http://.'); if (action === 'edit') { const id = positiveId(b.id); if (!id) return fail('Invalid listing id.'); const [listing] = await db.select().from(listings).where(eq(listings.id, id)); if (!listing || (!admin && listing.ownerId !== user.id)) return fail('Access denied.', 403); await db.update(listings).set({ ...data, status: admin ? listing.status : 'pending' }).where(eq(listings.id, listing.id)); } else await db.insert(listings).values({ ...data, ownerId: user.id }); return NextResponse.json({ success: true }); }
  if (action === 'save') { const id = positiveId(b.id); if (!id) return fail('Invalid listing id.'); const [target] = await db.select({ id: listings.id }).from(listings).where(and(eq(listings.id, id), eq(listings.status, 'approved'))); if (!target) return fail('Listing not found.', 404); const where = and(eq(saves.userId, user.id), eq(saves.listingId, id)); const found = await db.select({ id: saves.id }).from(saves).where(where); if (found.length) await db.delete(saves).where(where); else await db.insert(saves).values({ userId: user.id, listingId: id }).onConflictDoNothing(); return NextResponse.json({ success: true, saved: !found.length }); }
  if (action === 'review') { if (!(await consumeRateLimit(`review:${user.id}`, 5, 60))) return fail('Review limit reached. Please try again later.', 429); const id = positiveId(b.listingId), rating = Number(b.rating), comment = clean(b.comment, 2000); if (!id || !Number.isInteger(rating) || rating < 1 || rating > 5 || comment.length < 5) return fail('Choose a rating and write a short review.'); const [listing] = await db.select({ id: listings.id }).from(listings).where(and(eq(listings.id, id), eq(listings.status, 'approved'))); if (!listing) return fail('Listing not found.', 404); const [already] = await db.select({ id: reviews.id }).from(reviews).where(and(eq(reviews.listingId, id), eq(reviews.userId, user.id))).limit(1); if (already) return fail('You have already reviewed this listing.', 409); await db.insert(reviews).values({ listingId: id, userId: user.id, rating, comment }); return NextResponse.json({ success: true }); }
  if (!admin) return fail('Administrator access required.', 403);
  if (action === 'moderate') { const id = positiveId(b.id); if (!id || !['approved','rejected','pending'].includes(b.status)) return fail('Invalid moderation request.'); await db.update(listings).set({ status: b.status }).where(eq(listings.id, id)); }
  else if (action === 'feature') { const id = positiveId(b.id); if (!id) return fail('Invalid listing id.'); await db.update(listings).set({ featured: Boolean(b.featured) }).where(eq(listings.id, id)); }
  else if (action === 'content') { const key = clean(b.key, 80); if (!contentKeys.includes(key)) return fail('Invalid content key.'); const value = clean(b.value, key === 'articles' ? 150000 : key === 'categories' || key === 'locations' ? 3000 : 1000); if (!value) return fail('Content cannot be empty.'); if (key === 'articles') { let items: unknown; try { items = JSON.parse(value); } catch { return fail('Invalid article content.'); } if (!Array.isArray(items) || items.length > 30 || items.some(a => { if (!a || typeof a !== 'object') return true; const item = a as Record<string, unknown>; return typeof item.title !== 'string' || !item.title.trim() || item.title.length > 160 || typeof item.category !== 'string' || item.category.length > 80 || typeof item.image !== 'string' || !validHttpUrl(item.image) || typeof item.read !== 'string' || item.read.length > 30 || !Array.isArray(item.body) || !item.body.length || item.body.some(p => typeof p !== 'string' || p.length > 20000); })) return fail('Complete every article field and use a valid image URL. Maximum 30 stories.'); } if ((key === 'categories' || key === 'locations') && (value.split('\n').filter(Boolean).length > 40 || value.split('\n').some(s => s.length > 80))) return fail('Use up to 40 entries, each under 80 characters.'); await db.insert(content).values({ key, value }).onConflictDoUpdate({ target: content.key, set: { value } }); }
  else if (action === 'user') { const id = positiveId(b.id); if (!id || user.role !== 'superadmin' || id === user.id) return fail('This account cannot be changed.', 403); if (!['business','creator','staff'].includes(b.role)) return fail('Invalid role.'); const [target] = await db.select({ id: users.id, role: users.role }).from(users).where(eq(users.id, id)); if (!target || target.role === 'superadmin') return fail('Super administrator accounts are protected.', 403); await db.update(users).set({ role: b.role, suspended: Boolean(b.suspended) }).where(eq(users.id, id)); }
  else return fail('Unknown action.');
  return NextResponse.json({ success: true });
 } catch (error) { console.error('POST /api/platform failed', error); return fail('Could not complete your request. Please try again.', 500); }
}
